apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: "https://prometheus-community.github.io/helm-charts"
    releaseName: kube-prometheus-stack
    version: "72.9.0"
    valuesFile: values.yaml
    namespace: monitoring
    includeCrds: true
