apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: openbao
    repo: "https://openbao.github.io/openbao-helm"
    releaseName: openbao
    version: "0.12.0"
    valuesFile: values.yaml
    namespace: openbao
